[package]
name = "doggy"
version = "0.1.0"
authors = ["Fernando Cejas <fcejas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.9.0"
dialoguer = "0.4.0"
indicatif = "0.12.0"
cursive = "0.13"